name: SUSFS4KSU

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (empty)
        uses: actions/checkout@v4

      - name: Fetch commits from GitLab repo
        run: |
          # Clone specific branch from GitLab
          git clone --depth 30 --branch gki-android15-6.6 https://gitlab.com/simonpunk/susfs4ksu.git gki-android13-5.15
          cd gki-android13-5.15

          # Get latest commit message
          latest_msg=$(git log -1 --pretty=%s)
          echo "Latest commit message: $latest_msg"

          # Check if latest commit contains a version bump
          if echo "$latest_msg" | grep -qE "Bump version to v[0-9]+\.[0-9]+\.[0-9]+"; then
            version=$(echo "$latest_msg" | grep -oE "v[0-9]+\.[0-9]+\.[0-9]+")
          else
            # Look through recent commits for the latest version bump
            version=$(git log -50 --grep="Bump version to v" --pretty=format:"%s" \
              | grep -oE "v[0-9]+\.[0-9]+\.[0-9]+" \
              | head -n 1)
          fi

          echo "✅ Detected version: ${version:-unknown}"
          echo "VERSION=${version:-unknown}" >> $GITHUB_ENV

      - name: Use version variable
        run: |
          echo "✅ Latest detected SUSFS4KSU version: $VERSION"
